Some tweaks to notes helper script, and socket is now in $TMPDIR

diff --git a/sw/sh/notes b/sw/sh/notes
--- a/sw/sh/notes
+++ b/sw/sh/notes
@@ -1,23 +1,25 @@
-#!/usr/bin/env bash
+#!/bin/sh
 
 if [ -n "$TMUX" ]; then
-    # for some reason if I redir this to /dev/null or any other file on
-    # andrea, I get a long blocking event...
+    # for some reason if I redir this commands stdout to /dev/null or any other
+    # file on andrea, I get a long blocking event...
     #
     tmux set-window-option automatic-rename
     tmux rename-window notes
 fi
 
-if ! cd ~/n; then
-    echo "$0: failed to cd to notes dir, exiting"
-    exit
-fi
-
-my_dsock="${HOME}/notes.sock"
+my_notes_dir="${HOME}/n"
+my_dsock="${TMPDIR:-/tmp}/notes.sock"
 if [ -S "$my_dsock" ]; then
     dtach -a "$my_dsock"
 else
-    dtach -c "$my_dsock" vim -c 'normal zM' ~/n/ScratchNotes.viki
+
+    if ! cd "$my_notes_dir"; then
+        echo "$0: failed to cd to notes dir, exiting"
+        exit
+    fi
+
+    dtach -c "$my_dsock" vim -c 'normal zM' "${my_notes_dir}/ScratchNotes.viki"
 fi
 
 if [ -n "$TMUX" ]; then
