Overhaul sh services setup
	- info can now be recorded to ~/.sh/this-profile instead of
	  having to be passed as a mixture of arguments and environemt
	  varialbes.

	- ~/.sh/services stop now operates on whatever profile was
	  previous started.

	- more readable

diff --git a/.sh/services b/.sh/services
--- a/.sh/services
+++ b/.sh/services
@@ -8,48 +8,104 @@
 # if profile is supplied, network determination is ommitted. This is for a use
 # case like 'services stop work && services start', when changing networks.
 #
+# if profile is ommitted and the first argument is stop, the profile will be
+# looked up from the this-profile file. It is used to record the result of this
+# stuff.
+#
+########
+# TODO
+#   warn if trying to stop != current profile
+#   don't clobber NETWORK_PROFILE to non-existing-profile
+########
+
 
 MY_PROFILE_PATH="${HOME}/.sh"; export MY_PROFILE_PATH
+THIS_PROFILE="${MY_PROFILE_PATH}/this-profile"
+export MY_PROFILE_PATH THIS_PROFILE
 
 # include some utility functions
 #
 . "$MY_PROFILE_PATH/services.d/lib"
+assert_sh_services_environment
+
+# ensure environment is ok
+#
+ACTION="$1"
+MY_PROFILE="$2"
+if ! touch "$THIS_PROFILE"; then
+    echo "$0: unable to maintain state via $THIS_PROFILE - aborting!"
+    exit 1
+fi
+case "$ACTION" in
+    start|stop)
+        ;; 
+    *)
+        echo "Don't know how to handle $ACTION."
+        echo "Maybe run profile $PROFILE $ACTION directly?"
+        echo "Stopping."
+        exit 1
+        ;;
+esac
 
 
-if [ -n "$2" ]; then
-    MY_NETWORK_PROFILE="$2"
-else
+
+
+if [ "$ACTION" = "stop" -a -z "$MY_PROFILE" ]
+then # operate on current profile
+    if [ ! -r "$THIS_PROFILE" ]; then
+        echo "$0: error reading $THIS_PROFILE - aborting"
+        exit 127
+    fi
+    MY_PROFILE="`echo_this_profile NETWORK_PROFILE`"
+fi
+
+if [ "$ACTION" = "start" -a -z "$MY_PROFILE" ]
+then # detect it based on network connection
+
     case `echo_network_connection` in
         "Auto BSDNet") # home
-            NETWORK_NAME="BSDNet"
+            MY_NETWORK_NAME="BSDNet"
             ;;
         "Auto wegnet") # work
-            NETWORK_NAME="wegnet"
+            MY_NETWORK_NAME="wegnet"
             ;;
         "Auto SpideyMobile") # mobile (phone wifi)
-            NETWORK_NAME="mobile"
+            MY_NETWORK_NAME="mobile"
             ;;
         "Auto usb*") # mobile (currently phone via tether)
-            NETWORK_NAME="mobile"
+            MY_NETWORK_NAME="mobile"
             ;;
         "Auto eth0") # wired, check if wired or home
-            if ifconfig eth0 | grep "inet addr:" | grep -E "172\.1[67]\..+\..+" >/dev/null; then
-                NETWORK_NAME="engineering"
+            if ifconfig eth0 | grep "inet addr:" | \
+                grep -E "172\.1[67]\..+\..+" >/dev/null
+            then
+                MY_NETWORK_NAME="engineering"
             else
-                NETWORK_NAME="update $0 for this wired network!"
+                MY_NETWORK_NAME="update $0 for this wired network!"
             fi
             ;;
         *)
-            NETWORK_NAME="unknown"
+            MY_NETWORK_NAME="unknown"
             ;;
     esac
 
-    MY_NETWORK_PROFILE="`echo_network_profile $NETWORK_NAME`"
+    MY_PROFILE="`echo_network_profile $MY_NETWORK_NAME`"
+    write_this_profile NETWORK_NAME "$MY_NETWORK_NAME"
 fi
 
-export MY_PROFILE_PATH NETWORK_NAME MY_NETWORK_PROFILE
 
 
-services_d default "$1"
-services_d "$MY_NETWORK_PROFILE" "$1"
+
+# write information that should be exported to services_d().
+#
+write_this_profile NETWORK_PROFILE "$MY_PROFILE"
+
+# execute profiles
+#
+services_d default "$ACTION"
+services_d "$MY_PROFILE" "$ACTION"
+
+if [ "$ACTION" = "stop" ]; then # blank it as none is loaded
+    write_this_profile NETWORK_PROFILE ""
+fi
 
diff --git a/.sh/services.d/lib b/.sh/services.d/lib
--- a/.sh/services.d/lib
+++ b/.sh/services.d/lib
@@ -1,4 +1,28 @@
 # vim: set ft=sh :
+#
+# This file is designed to be sourced for its functions.
+#
+# You should be able to comply with assert_sh_services_environment() before
+# executing any of these functions.
+#
+
+# assert that the environment these functions need is exported
+#
+assert_sh_services_environment() {
+    if ! check_sh_services_environment; then
+        echo "sh services environment is missconfigured, abborting"
+        exit 1
+    fi
+}
+
+# check if the environment these functions need is exported
+# returns 0 if ok, > 0 if not ok
+#
+check_sh_services_environment() {
+    [ -z "$MY_PROFILE_PATH" ] && return 1
+    [ -z "$THIS_PROFILE" ] && return 1
+    return 0
+}
 
 services_d() {
     local w
@@ -6,7 +30,7 @@ services_d() {
     w="$MY_PROFILE_PATH/services.d/$1"
     shift 1
 	if [ -x "$w" ]; then
-	    "$w" "$@"
+	    echo "$w" "$@"
 	else
 	    echo "no $1 profile to execute! ($w)"
 	fi
@@ -15,7 +39,7 @@ services_d() {
 make_profile_link() {
     local w
 
-    w="${MY_PROFILE_PATH}/config.d/`basename $1`.${MY_NETWORK_PROFILE}"
+    w="${MY_PROFILE_PATH}/config.d/`basename $1`.`echo_this_profile NETWORK_PROFILE`"
     if [ -f "$w" ]; then
         ln -sf "$w" "${HOME}/.$1"
         return 0
@@ -30,7 +54,7 @@ rm_profile_link() {
 	fi
 }
 
-# Maps $NETWORK_NAME's to $MY_NETWORK_PROFILE's
+# Maps NETWORK_NAME's to NETWORK_PROFILE's
 #
 echo_network_profile() {
     case "$1" in
@@ -71,5 +95,67 @@ echo_network_connection() {
 	done
 
     echo "$output"
+}
+
+# extract info from the this-profile file.
+#
+# if no arguments: dump it sans comments.
+# for each argument (key), print the corrisonding value
+#
+echo_this_profile() {
+    local key
+
+    if [ ! -r "$THIS_PROFILE" ]; then
+        echo "unable to read $THIS_PROFILE" 1>&2
+        return 127
+    fi
+
+    if [ $# -eq 0 ]; then
+        cat "$THIS_PROFILE" | grep -v -E "^#"
+        return 0;
+    fi
+
+    for key in $@; do
+        grep -E "^${key}=" "$THIS_PROFILE"  | cut -d "=" -f 2- | tail -n 1
+            #
+            # force last entry (tail -n 1) to be returned, to *force* sanity.
+            # there should never be duplicates unless the user dicked with it.
+    done
+}
+
+write_this_profile() {
+    local key value
+
+    key="$1"
+    value="$2"
+
+    # erase the key
+    if [ -z "$value" ]; then
+        ed -s "$THIS_PROFILE" >/dev/null <<EOF
+    g/^${key}=/d
+EOF
+    fi
+
+    # test if value already exists
+    if [ -n "`echo_this_profile $key`" ]; then
+        # and replace
+        ed -s "$THIS_PROFILE" >/dev/null <<EOF
+        #cat <<EOF
+    $
+    ?^${key}=?
+    c
+${key}=${value}
+.
+    w
+    q
+EOF
+        return $?
+    fi
+
+    # else we can just append it.
+    #
+    # ed doesn't do locking so >> is just as safe \o/.
+    #
+    echo "${key}=${value}" >> $THIS_PROFILE
 }
 
